vich_uploader:
    db_driver: orm

    mappings:
       products:
            uri_prefix: /assets/images/property
            upload_destination: '%kernel.project_dir%/public/assets/images/property'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

